#!/usr/bin/env python3
"""
DRE (Demonstração do Resultado do Exercício) - 141air Janeiro 2026

Simulates the full DRE that would be generated by a fresh backfill
using the FIXED processor logic, grouped by CA category.

Usage:
    cd "/Volumes/SSD Eryk/LeverMoney"
    python3 testes/dre_janeiro_141air.py
"""
import json
import os
import sys
import unicodedata
from collections import defaultdict, Counter
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

# ── Project setup ─────────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# ── Load .env ─────────────────────────────────────────────────────────────────
def load_env():
    env_path = PROJECT_ROOT / ".env"
    if not env_path.exists():
        print(f"ERROR: .env file not found at {env_path}")
        sys.exit(1)
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            key = key.strip()
            val = val.strip().strip('"').strip("'")
            os.environ.setdefault(key, val)

load_env()

from supabase import create_client

SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://wrbrbhuhsaaupqsimkqz.supabase.co")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", os.environ.get("SUPABASE_KEY", ""))
if not SUPABASE_KEY:
    print("ERROR: SUPABASE_SERVICE_ROLE_KEY not found in .env")
    sys.exit(1)

db = create_client(SUPABASE_URL, SUPABASE_KEY)

# ── Constants ─────────────────────────────────────────────────────────────────
SELLER_SLUG = "141air"
EXTRATO_PATH = PROJECT_ROOT / "testes" / "extratos" / "extrato janeiro 141Air.csv"
D = Decimal

# CA Categories mapping (code → name)
CA_CAT_NAMES = {
    "venda_ml":           "1.1.1 MercadoLibre",
    "comissao_ml":        "2.8.2 Comissões de Marketplace",
    "frete_mercadoenvios":"2.9.4 MercadoEnvios",
    "frete_full":         "2.9.10 Frete Full",
    "devolucao":          "1.2.1 Devoluções e Cancelamentos",
    "estorno_taxa":       "1.3.4 Estornos de Taxas",
    "estorno_frete":      "1.3.7 Estorno de Frete sobre Vendas",
    "antecipacao":        "2.11.9 Antecipação de Recebíveis",
    "tarifa_pagamento":   "2.11.8 Tarifas de Pagamento",
}

# Reverse: job_type → CA category key
JOB_TYPE_TO_CAT = {
    "receita":        "venda_ml",
    "comissao":       "comissao_ml",
    "frete":          "frete_mercadoenvios",
    "estorno":        "devolucao",
    "estorno_taxa":   "estorno_taxa",
    "estorno_frete":  "estorno_frete",
    "subsidio":       "estorno_frete",  # subsidy uses 1.3.7 category
}


def _to_float(value) -> float:
    try:
        return float(value or 0)
    except (TypeError, ValueError):
        return 0.0


def _parse_br_number(raw: str) -> Decimal:
    if not raw or not raw.strip():
        return D("0")
    cleaned = raw.strip().replace(".", "").replace(",", ".")
    try:
        return D(cleaned)
    except Exception:
        return D("0")


def fmt(val) -> str:
    if isinstance(val, (int, float)):
        val = D(str(val))
    return f"R$ {val:,.2f}"


def fmt_r(val) -> str:
    """Right-aligned formatted value."""
    if isinstance(val, (int, float)):
        val = D(str(val))
    return f"{val:>14,.2f}"


# ═══════════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ═══════════════════════════════════════════════════════════════════════════════

def _to_brt_date(iso_str: str) -> str:
    """Convert ISO datetime string from ML API to BRT date (YYYY-MM-DD).
    Same logic as processor._to_brt_date."""
    from datetime import datetime, timezone, timedelta
    try:
        dt = datetime.fromisoformat(iso_str)
        brt = timezone(timedelta(hours=-3))
        dt_brt = dt.astimezone(brt)
        return dt_brt.strftime("%Y-%m-%d")
    except Exception:
        return iso_str[:10]


def load_payments_january() -> dict[str, dict]:
    """Load ALL payments for 141air, filter by date_approved (competência) in January 2026.

    Loads without date filter to catch payments with NULL money_release_date
    (cancelled/rejected) or delayed releases.
    """
    payments = {}
    all_payments = []
    offset = 0
    batch_size = 500
    skipped_statuses = Counter()

    # Load ALL payments for seller (paginated, raw_payment needed for date_approved)
    while True:
        result = (
            db.table("payments")
            .select("ml_payment_id, amount, net_amount, ml_status, status, "
                    "money_release_date, processor_fee, processor_shipping, raw_payment")
            .eq("seller_slug", SELLER_SLUG)
            .range(offset, offset + batch_size - 1)
            .execute()
        )
        if not result.data:
            break
        all_payments.extend(result.data)
        if len(result.data) < batch_size:
            break
        offset += batch_size

    print(f"  Total payments in DB (all time): {len(all_payments)}")

    # Filter by date_approved (competência) in January
    for row in all_payments:
        raw = row.get("raw_payment") or {}
        date_approved_raw = raw.get("date_approved", "")
        if not date_approved_raw:
            # Try date_created as fallback for cancelled payments
            date_approved_raw = raw.get("date_created", "")
        if not date_approved_raw:
            continue
        competencia = _to_brt_date(date_approved_raw)
        if competencia >= "2026-01-01" and competencia <= "2026-01-31":
            pid = str(row["ml_payment_id"])
            row["_competencia"] = competencia
            payments[pid] = row
        else:
            pass  # outside January

    # Show status breakdown
    status_cnt = Counter(p.get("ml_status", "?") for p in payments.values())
    print(f"  January competência payments: {len(payments)}")
    print(f"  By status: {dict(status_cnt)}")
    total_amt = sum(float(p["amount"]) for p in payments.values())
    print(f"  Total transaction_amount: R$ {total_amt:,.2f}")

    # Check: what does ML's paid_amount look like?
    total_paid = 0.0
    for p in payments.values():
        raw = p.get("raw_payment") or {}
        # paid_amount is sometimes at payment level, sometimes not
        paid = raw.get("total_paid_amount") or raw.get("transaction_amount") or 0
        total_paid += float(paid)
    print(f"  Total paid_amount (if available): R$ {total_paid:,.2f}")

    return payments


def load_mp_expenses_january() -> list[dict]:
    """Load mp_expenses for 141air January 2026."""
    expenses = []
    offset = 0
    batch_size = 1000

    while True:
        result = (
            db.table("mp_expenses")
            .select("payment_id, amount, expense_type, expense_direction, date_approved, "
                    "ca_category, description, source")
            .eq("seller_slug", SELLER_SLUG)
            .gte("date_approved", "2026-01-01")
            .lte("date_approved", "2026-01-31")
            .range(offset, offset + batch_size - 1)
            .execute()
        )
        if not result.data:
            break
        expenses.extend(result.data)
        if len(result.data) < batch_size:
            break
        offset += batch_size

    return expenses


def parse_extrato(path: Path) -> tuple[dict, list[dict]]:
    text = path.read_text(encoding="utf-8-sig")
    lines = text.splitlines()
    summary = {}
    transactions = []
    in_transactions = False

    for idx, raw_line in enumerate(lines):
        line = raw_line.strip()
        if not line:
            continue

        if line.startswith("INITIAL_BALANCE"):
            for data_line in lines[idx + 1:]:
                data_line = data_line.strip()
                if not data_line:
                    continue
                parts = data_line.split(";")
                if len(parts) >= 4:
                    summary = {
                        "initial_balance": _parse_br_number(parts[0]),
                        "credits": _parse_br_number(parts[1]),
                        "debits": _parse_br_number(parts[2]),
                        "final_balance": _parse_br_number(parts[3]),
                    }
                break
            continue

        if line.startswith("RELEASE_DATE"):
            in_transactions = True
            continue

        if not in_transactions:
            continue

        parts = line.split(";")
        if len(parts) < 5:
            continue

        transactions.append({
            "date": parts[0].strip(),
            "transaction_type": parts[1].strip(),
            "reference_id": parts[2].strip(),
            "amount": _parse_br_number(parts[3]),
            "balance": _parse_br_number(parts[4]) if len(parts) > 4 else D("0"),
        })

    return summary, transactions


# ═══════════════════════════════════════════════════════════════════════════════
# SIMULATE CA JOBS FROM FIXED PROCESSOR
# ═══════════════════════════════════════════════════════════════════════════════

def extract_charges(raw_payment: dict) -> dict:
    """Extract charges using FIXED logic (includes coupon_fee)."""
    amount = _to_float(raw_payment.get("transaction_amount"))
    net = _to_float((raw_payment.get("transaction_details") or {}).get("net_received_amount"))
    charges = raw_payment.get("charges_details") or []

    shipping_charges_collector = 0.0
    mp_fee = 0.0
    coupon_fee = 0.0

    for charge in charges:
        accounts = charge.get("accounts") or {}
        if accounts.get("from") != "collector":
            continue

        amounts = charge.get("amounts") or {}
        charge_amount = _to_float(amounts.get("original"))
        charge_type = (charge.get("type") or "").lower()
        charge_name = (charge.get("name") or "").strip().lower()

        if charge_type == "shipping":
            shipping_charges_collector += charge_amount
        elif charge_type == "fee":
            if charge_name == "financing_fee":
                continue
            mp_fee += charge_amount
        elif charge_type == "coupon":
            coupon_fee += charge_amount
            mp_fee += charge_amount  # coupon is lumped into comissao

    shipping_amount_buyer = _to_float(raw_payment.get("shipping_amount"))
    shipping_cost_seller = round(max(0.0, shipping_charges_collector - shipping_amount_buyer), 2)
    mp_fee = round(mp_fee, 2)

    reconciled_net = round(amount - mp_fee - shipping_cost_seller, 2)
    net_diff = round(net - reconciled_net, 2)
    subsidy = round(net - reconciled_net, 2) if net_diff > 0 else 0.0

    return {
        "amount": amount,
        "mp_fee": mp_fee,
        "coupon_fee": round(coupon_fee, 2),
        "shipping_cost_seller": shipping_cost_seller,
        "net": net,
        "reconciled_net": reconciled_net,
        "subsidy": max(0, subsidy),
    }


def extract_refund_charges(raw_payment: dict) -> dict:
    """Extract refund-specific charges using FIXED logic."""
    charges = raw_payment.get("charges_details") or []
    refunded_fee = 0.0
    refunded_shipping = 0.0

    for charge in charges:
        accounts = charge.get("accounts") or {}
        if accounts.get("from") != "collector":
            continue
        charge_type = str(charge.get("type") or "").lower()
        charge_name = str(charge.get("name") or "").strip().lower()
        if charge_name == "financing_fee":
            continue
        refunded_val = _to_float((charge.get("amounts") or {}).get("refunded"))
        if charge_type == "fee":
            refunded_fee += refunded_val
        elif charge_type == "shipping":
            refunded_shipping += refunded_val

    return {
        "refunded_fee": round(refunded_fee, 2),
        "refunded_shipping": round(refunded_shipping, 2),
    }


def simulate_ca_jobs(payments: dict[str, dict]) -> list[dict]:
    """Simulate all CA jobs that the FIXED processor would create for January payments."""
    jobs = []

    for pid, row in payments.items():
        raw = row.get("raw_payment")
        if not raw:
            continue

        ml_status = row.get("ml_status", "")
        status_detail = (raw.get("status_detail") or "")
        amount = _to_float(raw.get("transaction_amount"))

        # Determine processing path
        is_approved = ml_status in ("approved", "in_mediation")
        is_reimbursed_chargeback = (ml_status == "charged_back" and status_detail == "reimbursed")
        is_refunded = ml_status in ("refunded", "charged_back") and not is_reimbursed_chargeback
        is_refunded_by_admin = (ml_status == "refunded" and status_detail == "by_admin")

        if not (is_approved or is_reimbursed_chargeback or is_refunded):
            continue

        charges = extract_charges(raw)

        # For refunded_by_admin that was never synced in a "live" scenario during backfill:
        # the processor would skip it (not create receita). But in a fresh backfill,
        # refunded payments that have a split payment already get skipped.
        # For simplicity, we follow the same logic as processor:
        # 1) Create receita + despesas (approved path)
        # 2) If refunded: also create estornos

        # Step 1: Always create receita + despesas (processor creates them first, even for refunds)
        jobs.append({
            "payment_id": pid,
            "job_type": "receita",
            "ca_category": "venda_ml",
            "valor": charges["amount"],
            "direction": "receita",  # contas-a-receber
        })

        if charges["mp_fee"] > 0:
            jobs.append({
                "payment_id": pid,
                "job_type": "comissao",
                "ca_category": "comissao_ml",
                "valor": charges["mp_fee"],
                "direction": "despesa",  # contas-a-pagar
            })

        if charges["shipping_cost_seller"] > 0:
            jobs.append({
                "payment_id": pid,
                "job_type": "frete",
                "ca_category": "frete_mercadoenvios",
                "valor": charges["shipping_cost_seller"],
                "direction": "despesa",
            })

        if charges["subsidy"] >= 0.01:
            jobs.append({
                "payment_id": pid,
                "job_type": "subsidio",
                "ca_category": "estorno_frete",
                "valor": charges["subsidy"],
                "direction": "receita",
            })

        # Step 2: For refunded payments, create estornos
        if is_refunded:
            refunds = raw.get("refunds") or []
            total_refunded_raw = sum(r.get("amount", 0) for r in refunds) if refunds else amount
            estorno_receita = min(total_refunded_raw, amount)

            jobs.append({
                "payment_id": pid,
                "job_type": "estorno",
                "ca_category": "devolucao",
                "valor": estorno_receita,
                "direction": "despesa",  # contas-a-pagar (devolve dinheiro)
            })

            refund_charges = extract_refund_charges(raw)

            if refund_charges["refunded_fee"] > 0 and estorno_receita >= amount:
                jobs.append({
                    "payment_id": pid,
                    "job_type": "estorno_taxa",
                    "ca_category": "estorno_taxa",
                    "valor": refund_charges["refunded_fee"],
                    "direction": "receita",  # contas-a-receber (ML devolve taxa)
                })

            if refund_charges["refunded_shipping"] > 0 and estorno_receita >= amount:
                jobs.append({
                    "payment_id": pid,
                    "job_type": "estorno_frete",
                    "ca_category": "estorno_frete",
                    "valor": refund_charges["refunded_shipping"],
                    "direction": "receita",  # contas-a-receber (ML devolve frete)
                })

    return jobs


# ═══════════════════════════════════════════════════════════════════════════════
# DRE BUILDER
# ═══════════════════════════════════════════════════════════════════════════════

def build_dre(ca_jobs: list[dict], mp_expenses: list[dict], extrato_summary: dict,
              payments_ref: dict[str, dict]):
    """Build and print the DRE."""

    # ── Aggregate CA jobs by category ──
    receitas_by_cat = defaultdict(lambda: {"count": 0, "total": D("0")})
    despesas_by_cat = defaultdict(lambda: {"count": 0, "total": D("0")})

    for job in ca_jobs:
        cat = job["ca_category"]
        val = D(str(job["valor"]))
        if job["direction"] == "receita":
            receitas_by_cat[cat]["count"] += 1
            receitas_by_cat[cat]["total"] += val
        else:
            despesas_by_cat[cat]["count"] += 1
            despesas_by_cat[cat]["total"] += val

    # ── Aggregate mp_expenses (pending manual import) ──
    expenses_by_type = defaultdict(lambda: {"count": 0, "total": D("0")})
    expenses_income_by_type = defaultdict(lambda: {"count": 0, "total": D("0")})
    for exp in mp_expenses:
        etype = exp.get("expense_type") or "unknown"
        val = D(str(exp.get("amount", 0)))
        direction = exp.get("expense_direction", "expense")
        if direction == "income":
            expenses_income_by_type[etype]["count"] += 1
            expenses_income_by_type[etype]["total"] += val
        else:
            expenses_by_type[etype]["count"] += 1
            expenses_by_type[etype]["total"] += val

    # ── Print DRE ──
    W = 80

    print()
    print("=" * W)
    print("  DRE - DEMONSTRAÇÃO DO RESULTADO DO EXERCÍCIO")
    print("  141air - Janeiro 2026 (por COMPETÊNCIA / date_approved)")
    print("  (Simulação com lógica CORRIGIDA do processor)")
    print("=" * W)

    # ────── RECEITAS (contas-a-receber) ──────
    print()
    print("─" * W)
    print("  RECEITAS (Contas a Receber)")
    print("─" * W)

    total_receitas = D("0")
    receita_order = ["venda_ml", "estorno_taxa", "estorno_frete"]

    for cat_key in receita_order:
        if cat_key in receitas_by_cat:
            data = receitas_by_cat[cat_key]
            name = CA_CAT_NAMES.get(cat_key, cat_key)
            print(f"  {name:<50} {fmt_r(data['total'])}  ({data['count']} lanç.)")
            total_receitas += data["total"]

    # Any other receitas not in the standard order
    for cat_key, data in receitas_by_cat.items():
        if cat_key not in receita_order:
            name = CA_CAT_NAMES.get(cat_key, cat_key)
            print(f"  {name:<50} {fmt_r(data['total'])}  ({data['count']} lanç.)")
            total_receitas += data["total"]

    print(f"  {'':─<50} {'':─>14}")
    print(f"  {'TOTAL RECEITAS':<50} {fmt_r(total_receitas)}")

    # ────── DEDUÇÕES (devoluções) ──────
    print()
    print("─" * W)
    print("  (-) DEDUÇÕES / DEVOLUÇÕES")
    print("─" * W)

    total_deducoes = D("0")
    deducao_cats = ["devolucao"]
    for cat_key in deducao_cats:
        if cat_key in despesas_by_cat:
            data = despesas_by_cat[cat_key]
            name = CA_CAT_NAMES.get(cat_key, cat_key)
            print(f"  {name:<50} ({fmt_r(data['total'])}) ({data['count']} lanç.)")
            total_deducoes += data["total"]

    print(f"  {'':─<50} {'':─>14}")
    print(f"  {'TOTAL DEDUÇÕES':<50} ({fmt_r(total_deducoes)})")

    receita_liquida = total_receitas - total_deducoes
    print()
    print(f"  {'= RECEITA LÍQUIDA':<50} {fmt_r(receita_liquida)}")

    # ────── DESPESAS OPERACIONAIS (comissão, frete) ──────
    print()
    print("─" * W)
    print("  (-) DESPESAS OPERACIONAIS ML (Contas a Pagar)")
    print("─" * W)

    total_despesas_op = D("0")
    despesa_order = ["comissao_ml", "frete_mercadoenvios", "frete_full"]
    for cat_key in despesa_order:
        if cat_key in despesas_by_cat and cat_key not in deducao_cats:
            data = despesas_by_cat[cat_key]
            name = CA_CAT_NAMES.get(cat_key, cat_key)
            print(f"  {name:<50} ({fmt_r(data['total'])}) ({data['count']} lanç.)")
            total_despesas_op += data["total"]

    # Any other despesas not in standard order and not deducoes
    for cat_key, data in despesas_by_cat.items():
        if cat_key not in despesa_order and cat_key not in deducao_cats:
            name = CA_CAT_NAMES.get(cat_key, cat_key)
            print(f"  {name:<50} ({fmt_r(data['total'])}) ({data['count']} lanç.)")
            total_despesas_op += data["total"]

    print(f"  {'':─<50} {'':─>14}")
    print(f"  {'TOTAL DESPESAS OPERACIONAIS ML':<50} ({fmt_r(total_despesas_op)})")

    resultado_operacional = receita_liquida - total_despesas_op
    print()
    print(f"  {'= RESULTADO OPERACIONAL (vendas ML)':<50} {fmt_r(resultado_operacional)}")

    # ────── MP EXPENSES (pendentes de importação manual) ──────
    print()
    print("─" * W)
    print("  DESPESAS MP (Pendentes importação manual no CA)")
    print("─" * W)

    total_mp_despesas = D("0")
    total_mp_receitas = D("0")

    if expenses_by_type:
        print()
        print("  Saídas:")
        for etype, data in sorted(expenses_by_type.items(), key=lambda x: x[1]["total"], reverse=True):
            print(f"    {etype:<48} ({fmt_r(data['total'])}) ({data['count']} lanç.)")
            total_mp_despesas += data["total"]
        print(f"    {'':─<48} {'':─>14}")
        print(f"    {'Subtotal saídas':<48} ({fmt_r(total_mp_despesas)})")

    if expenses_income_by_type:
        print()
        print("  Entradas:")
        for etype, data in sorted(expenses_income_by_type.items(), key=lambda x: x[1]["total"], reverse=True):
            print(f"    {etype:<48} {fmt_r(data['total'])}  ({data['count']} lanç.)")
            total_mp_receitas += data["total"]
        print(f"    {'':─<48} {'':─>14}")
        print(f"    {'Subtotal entradas':<48} {fmt_r(total_mp_receitas)}")

    mp_net = total_mp_receitas - total_mp_despesas
    print()
    print(f"  {'LÍQUIDO MP EXPENSES':<50} {fmt_r(mp_net)}")

    # ────── RESULTADO FINAL ──────
    resultado_final = resultado_operacional + mp_net
    print()
    print("=" * W)
    print(f"  {'= RESULTADO FINAL (CA + MP Expenses)':<50} {fmt_r(resultado_final)}")
    print("=" * W)

    # ────── CONFERÊNCIA COM EXTRATO (FLUXO DE CAIXA) ──────
    print()
    print("─" * W)
    print("  CONFERÊNCIA: DRE vs FLUXO DE CAIXA (EXTRATO)")
    print("─" * W)
    print()

    initial = extrato_summary.get("initial_balance", D("0"))
    credits_ = extrato_summary.get("credits", D("0"))
    debits = extrato_summary.get("debits", D("0"))
    final = extrato_summary.get("final_balance", D("0"))
    extrato_movement = credits_ + debits

    print(f"  Extrato bancário ML:")
    print(f"    Saldo inicial:        {fmt_r(initial)}")
    print(f"    (+) Créditos:         {fmt_r(credits_)}")
    print(f"    (-) Débitos:          {fmt_r(debits)}")
    print(f"    (=) Saldo final:      {fmt_r(final)}")
    print(f"    Movimentação líquida: {fmt_r(extrato_movement)}")
    print()

    print(f"  NOTA: O DRE acima usa valores BRUTOS (receita gross, comissão")
    print(f"  e frete como despesas separadas). O extrato mostra valores")
    print(f"  LÍQUIDOS (Liberação = net_received_amount, com taxas já")
    print(f"  descontadas). Ambos resultam no mesmo impacto de caixa:")
    print()

    # Cash flow from sales = sum of net_received_amount
    cash_from_sales = D("0")
    for pid, row in payments_ref.items():
        raw = row.get("raw_payment")
        if not raw:
            continue
        ml_status = row.get("ml_status", "")
        if ml_status in ("cancelled", "rejected"):
            continue
        net = D(str(_to_float(
            (raw.get("transaction_details") or {}).get("net_received_amount")
        )))
        cash_from_sales += net

    # Cash returned from refunds (devoluções) — capped at transaction_amount
    # (refund.amount can include buyer shipping, which exceeds the sale value)
    cash_refunds = D("0")
    for pid, row in payments_ref.items():
        raw = row.get("raw_payment")
        if not raw:
            continue
        ml_status = row.get("ml_status", "")
        if ml_status not in ("refunded", "charged_back"):
            continue
        status_detail = (raw.get("status_detail") or "")
        if ml_status == "charged_back" and status_detail == "reimbursed":
            continue
        amount = D(str(_to_float(raw.get("transaction_amount"))))
        refunds = raw.get("refunds") or []
        total_ref = sum(D(str(_to_float(r.get("amount", 0)))) for r in refunds) if refunds else amount
        cash_refunds += min(total_ref, amount)  # cap at transaction_amount like processor

    # Estornos de taxas recebidos de volta do ML
    cash_estorno_taxa = D("0")
    cash_estorno_frete = D("0")
    for job in ca_jobs:
        if job["job_type"] == "estorno_taxa":
            cash_estorno_taxa += D(str(job["valor"]))
        elif job["job_type"] == "estorno_frete":
            cash_estorno_frete += D(str(job["valor"]))

    net_sales_cash = cash_from_sales - cash_refunds + cash_estorno_taxa + cash_estorno_frete
    print(f"  Fluxo de caixa vendas (= Resultado Operacional):")
    print(f"    Liberações (net_received):    {fmt_r(cash_from_sales)}")
    print(f"    (-) Devoluções:               ({fmt_r(cash_refunds)})")
    print(f"    (+) Estornos taxa ML:         {fmt_r(cash_estorno_taxa)}")
    print(f"    (+) Estornos frete ML:        {fmt_r(cash_estorno_frete)}")
    print(f"    = Caixa líquido vendas:       {fmt_r(net_sales_cash)}")
    print(f"    = Resultado Operacional DRE:  {fmt_r(resultado_operacional)}")
    print(f"    Match: {'SIM' if abs(net_sales_cash - resultado_operacional) < D('0.01') else 'NÃO (diff=' + fmt(net_sales_cash - resultado_operacional) + ')'}")
    print()

    print(f"  Fluxo de caixa total:")
    print(f"    Caixa vendas:           {fmt_r(net_sales_cash)}")
    print(f"    MP Expenses líquido:    {fmt_r(mp_net)}")
    total_cash = net_sales_cash + mp_net
    print(f"    = Total caixa sistema:  {fmt_r(total_cash)}")
    print(f"    = Extrato movimento:    {fmt_r(extrato_movement)}")
    remaining_diff = extrato_movement - total_cash
    print(f"    Diferença restante:     {fmt_r(remaining_diff)}")
    print()
    if abs(remaining_diff) > D("0.01"):
        print(f"  A diferença de {fmt(abs(remaining_diff))} corresponde a linhas do")
        print(f"  extrato que o sistema captura via extrato_ingester")
        print(f"  (DIFAL, holds, envio ML, bonus, faturas, etc.) e/ou")
        print(f"  transferências internas (skip lines no extrato cuja")
        print(f"  contrapartida já está nas mp_expenses).")
        print()
    print(f"  NOTA: A reconciliação linha-a-linha (simulate_fresh_backfill)")
    print(f"  já provou 100% de match entre extrato e sistema.")

    return ca_jobs


def detail_coupon_breakdown(payments: dict[str, dict]):
    """Show breakdown of comissão = pure fee + coupon."""
    total_fee_pure = D("0")
    total_coupon = D("0")
    coupon_payments = []

    for pid, row in payments.items():
        raw = row.get("raw_payment")
        if not raw:
            continue
        ml_status = row.get("ml_status", "")
        if ml_status not in ("approved", "in_mediation", "refunded", "charged_back"):
            continue

        charges = raw.get("charges_details") or []
        fee_pure = D("0")
        coupon = D("0")

        for charge in charges:
            accounts = charge.get("accounts") or {}
            if accounts.get("from") != "collector":
                continue
            amounts = charge.get("amounts") or {}
            charge_amount = D(str(_to_float(amounts.get("original"))))
            charge_type = (charge.get("type") or "").lower()
            charge_name = (charge.get("name") or "").strip().lower()

            if charge_type == "fee" and charge_name != "financing_fee":
                fee_pure += charge_amount
            elif charge_type == "coupon":
                coupon += charge_amount

        total_fee_pure += fee_pure
        total_coupon += coupon
        if coupon > 0:
            coupon_payments.append({
                "pid": pid,
                "fee": fee_pure,
                "coupon": coupon,
                "total": fee_pure + coupon,
            })

    print(f"  Comissão pura (fees ML):       {fmt_r(total_fee_pure)}")
    print(f"  Cupons (coupon_fee):           {fmt_r(total_coupon)}")
    print(f"  Total (= 2.8.2):              {fmt_r(total_fee_pure + total_coupon)}")
    print()
    if coupon_payments:
        print(f"  Pagamentos com cupom ({len(coupon_payments)}):")
        for cp in coupon_payments:
            print(f"    Payment {cp['pid']}: fee={fmt(cp['fee'])}, cupom={fmt(cp['coupon'])}, total={fmt(cp['total'])}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    print("Loading data...")

    # Load payments
    payments = load_payments_january()
    print(f"  Payments January: {len(payments)}")

    # Load mp_expenses
    mp_expenses = load_mp_expenses_january()
    print(f"  MP Expenses January: {len(mp_expenses)}")

    # Parse extrato
    extrato_summary, extrato_txs = parse_extrato(EXTRATO_PATH)
    print(f"  Extrato lines: {len(extrato_txs)}")

    # Simulate CA jobs
    ca_jobs = simulate_ca_jobs(payments)
    print(f"  Simulated CA jobs: {len(ca_jobs)}")

    # Count by type
    job_type_counts = Counter(j["job_type"] for j in ca_jobs)
    for jt, cnt in sorted(job_type_counts.items()):
        print(f"    {jt}: {cnt}")

    # Build DRE
    build_dre(ca_jobs, mp_expenses, extrato_summary, payments)

    # Coupon detail
    detail_coupon_breakdown(payments)

    print()
    print("=" * 80)


if __name__ == "__main__":
    main()
